import "./globals.css";
import Nav from "./(components)/Nav";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Ticketing App",
  description: "Generated by Tevin Davis",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
